version: "3.9"
name: auth_standalone

services:
  auth_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.auth

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env.auth
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
